module.exports = {
	RECEIVE_TEACHERS: "RECEIVE_TEACHERS",
	RECEIVE_STUDENTS: "RECEIVE_STUDENTS",
	RECEIVE_QUIZZES: "RECEIVE_QUIZZES",
	//SHOWEACS
	SHOW_TEACHER: "SHOW_TEACHER", 
	SHOW_STUDENT: "SHOW_STUDENT",
	SHOW_QUIZZ: "SHOW_QUIZZ"  

}// end exports

