module.exports = {
	RECEIVE_TEACHERS: "RECEIVE_TEACHERS",
	RECEIVE_STUDENTS: "RECEIVE_STUDENTS",
	RECEIVE_QUIZZES: "RECEIVE_QUIZZES",
	//SHOWEACS
	SHOW_TEACHER: "SHOW_TEACHER", 
	SHOW_STUDENT: "SHOW_STUDENT",
	SHOW_QUIZ: "SHOW_QUIZ",  
	//UPDATE UI
	UPDATE_SCORES: "UPDATE_SCORES"
}// end exports

